### ISSUE TITLE
How to handle case when Edge doesn't know from/to vertices?

### ISSUE THREAD

**Issue by gitbuda** [memgraph/schema#4]
The problem happens if the implementation doesn't have data about from/to vertices directly under the edge.

Proposal#1 - making `start_node_id`, `end_node_id` and `properties` optional:
```
"edges": [
    {
        "id": 0,
        "edge_type": ":IS_FAMILY",
        "start_node_id": 0,
        "end_node_id": 1,
        "count": 5
    },
    {
        "id": 1,
        "edge_type": ":IS_FAMILY",
        "count": 10,
        "properties": [
            {
                "key": "since",
                "count": 1,
		"filling_factor": "100",
                "types": [
                    {
                        "type": "Integer",
                        "count": 1
                    }
                ]
            }
        ]
    }
]
```

**Comment by tonilastre** [comment]
When does this happen - when edge doesn't know from/to vertices?

**Comment by gitbuda** [comment]
> When does this happen - when edge doesn't know from/to vertices?

Yes, in Memgraph's `IN_MEMORY_TRANSACTIONAL` mode, on property update, there is no info about from & to nodes because the implementation depends on transactional deltes which currently don't have that info. But, I think we have a solution, the "EdgePropertyUpdateDelta", is going to be extended with `from` info, that's enough to extract both `from` and `to` during the schema update without increasing memory usage because the delta is a union object and info fits below current maximum stack size.

Most likely, this issue will be closed.

**Comment by gitbuda** [comment]
Closing this because it became obsolete in the meantime (we managed to come up with a good enough implementation).
